name: PR Comment

on:
    issue_comment:
        types:
            - created

jobs:
    pr_comment:
        if: ${{ github.event.issue.pull_request && github.event.comment.body == 'comment' }}
        runs-on: [self-hosted]

        steps:
            - uses: actions/github-script@v3
              id: get-pr
              with:
                  script: |
                      const request = {
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        pull_number: context.issue.number
                      }
                      core.info(`Getting PR #${request.pull_number} from ${request.owner}/${request.repo}`)
                      try {
                        const result = await github.pulls.get(request)
                        console.log(result)
                        return result.data
                      } catch (err) {
                        core.setFailed(`Request failed with error ${err}`)
                      }
            - uses: actions/checkout@v2
              with:
                  repository: ${{ fromJSON(steps.get-pr.outputs.result).head.repo.full_name }}
                  ref: ${{ fromJSON(steps.get-pr.outputs.result).head.sha }} # or .head.ref for branch name
            - run: echo "${{steps.get-pr.outputs.result}}"
            - run: echo "${{ fromJSON(steps.get-pr.outputs.result).head.sha }}"
            - uses: actions/setup-node@v1
              with:
                  node-version: '16.8.0'
            - run: echo done
